-- Insert all 500+ universities and colleges from the diplomas page into the Diplomas category
WITH category AS (
  SELECT id FROM product_categories WHERE slug = 'diplomas'
),
all_diplomas AS (
  SELECT * FROM (VALUES
    ('Harvard University', 'harvard-university', 'Cambridge, MA', 15000, 'USA'),
    ('Stanford University', 'stanford-university', 'Stanford, CA', 15000, 'USA'),
    ('Massachusetts Institute of Technology (MIT)', 'mit', 'Cambridge, MA', 15000, 'USA'),
    ('University of California, Berkeley', 'uc-berkeley', 'Berkeley, CA', 12000, 'USA'),
    ('Princeton University', 'princeton-university', 'Princeton, NJ', 15000, 'USA'),
    ('Yale University', 'yale-university', 'New Haven, CT', 15000, 'USA'),
    ('Columbia University', 'columbia-university', 'New York, NY', 15000, 'USA'),
    ('University of Chicago', 'university-chicago', 'Chicago, IL', 14000, 'USA'),
    ('California Institute of Technology (Caltech)', 'caltech', 'Pasadena, CA', 15000, 'USA'),
    ('Johns Hopkins University', 'johns-hopkins', 'Baltimore, MD', 14000, 'USA'),
    ('University of Pennsylvania', 'upenn', 'Philadelphia, PA', 14000, 'USA'),
    ('Cornell University', 'cornell-university', 'Ithaca, NY', 14000, 'USA'),
    ('University of Michigan', 'university-michigan', 'Ann Arbor, MI', 12000, 'USA'),
    ('Northwestern University', 'northwestern-university', 'Evanston, IL', 14000, 'USA'),
    ('Duke University', 'duke-university', 'Durham, NC', 14000, 'USA'),
    ('University of California, Los Angeles (UCLA)', 'ucla', 'Los Angeles, CA', 12000, 'USA'),
    ('Brown University', 'brown-university', 'Providence, RI', 14000, 'USA'),
    ('Dartmouth College', 'dartmouth-college', 'Hanover, NH', 14000, 'USA'),
    ('Vanderbilt University', 'vanderbilt-university', 'Nashville, TN', 13000, 'USA'),
    ('Rice University', 'rice-university', 'Houston, TX', 13000, 'USA'),
    ('Washington University in St. Louis', 'wustl', 'St. Louis, MO', 13000, 'USA'),
    ('University of Notre Dame', 'notre-dame', 'Notre Dame, IN', 13000, 'USA'),
    ('University of California, San Diego', 'ucsd', 'San Diego, CA', 12000, 'USA'),
    ('Emory University', 'emory-university', 'Atlanta, GA', 13000, 'USA'),
    ('Georgetown University', 'georgetown-university', 'Washington, DC', 13000, 'USA'),
    ('Carnegie Mellon University', 'cmu', 'Pittsburgh, PA', 14000, 'USA'),
    ('University of Southern California', 'usc', 'Los Angeles, CA', 13000, 'USA'),
    ('University of Virginia', 'uva', 'Charlottesville, VA', 12000, 'USA'),
    ('New York University', 'nyu', 'New York, NY', 13000, 'USA'),
    ('Tufts University', 'tufts-university', 'Medford, MA', 13000, 'USA'),
    ('University of North Carolina at Chapel Hill', 'unc-chapel-hill', 'Chapel Hill, NC', 11000, 'USA'),
    ('Boston College', 'boston-college', 'Chestnut Hill, MA', 12000, 'USA'),
    ('University of California, Santa Barbara', 'ucsb', 'Santa Barbara, CA', 11000, 'USA'),
    ('University of California, Irvine', 'uci', 'Irvine, CA', 11000, 'USA'),
    ('Georgia Institute of Technology', 'georgia-tech', 'Atlanta, GA', 12000, 'USA'),
    ('University of Florida', 'university-florida', 'Gainesville, FL', 11000, 'USA'),
    ('Boston University', 'boston-university', 'Boston, MA', 12000, 'USA'),
    ('University of Texas at Austin', 'ut-austin', 'Austin, TX', 11000, 'USA'),
    ('University of Wisconsin-Madison', 'uw-madison', 'Madison, WI', 11000, 'USA'),
    ('University of Illinois at Urbana-Champaign', 'uiuc', 'Champaign, IL', 11000, 'USA'),
    ('University of Washington', 'uw-seattle', 'Seattle, WA', 11000, 'USA'),
    ('Ohio State University', 'ohio-state', 'Columbus, OH', 10000, 'USA'),
    ('Pennsylvania State University', 'penn-state', 'University Park, PA', 10000, 'USA'),
    ('Purdue University', 'purdue-university', 'West Lafayette, IN', 10000, 'USA'),
    ('University of California, Davis', 'ucdavis', 'Davis, CA', 11000, 'USA'),
    ('University of Minnesota', 'umn', 'Minneapolis, MN', 10000, 'USA'),
    ('University of Maryland', 'umd', 'College Park, MD', 10000, 'USA'),
    ('Rutgers University', 'rutgers', 'New Brunswick, NJ', 10000, 'USA'),
    ('Texas A&M University', 'texas-am', 'College Station, TX', 10000, 'USA'),
    ('University of Pittsburgh', 'pitt', 'Pittsburgh, PA', 10000, 'USA'),
    ('Michigan State University', 'michigan-state', 'East Lansing, MI', 9500, 'USA'),
    ('University of Miami', 'miami', 'Coral Gables, FL', 11000, 'USA'),
    ('Indiana University Bloomington', 'iu-bloomington', 'Bloomington, IN', 9500, 'USA'),
    ('University of Arizona', 'arizona', 'Tucson, AZ', 9500, 'USA'),
    ('Arizona State University', 'asu', 'Tempe, AZ', 9500, 'USA'),
    ('University of Colorado Boulder', 'cu-boulder', 'Boulder, CO', 10000, 'USA'),
    ('University of Georgia', 'uga', 'Athens, GA', 9500, 'USA'),
    ('North Carolina State University', 'nc-state', 'Raleigh, NC', 9500, 'USA'),
    ('Virginia Tech', 'virginia-tech', 'Blacksburg, VA', 9500, 'USA'),
    ('University of Iowa', 'iowa', 'Iowa City, IA', 9500, 'USA'),
    ('Clemson University', 'clemson', 'Clemson, SC', 9500, 'USA'),
    ('University of Connecticut', 'uconn', 'Storrs, CT', 10000, 'USA'),
    ('University of Massachusetts Amherst', 'umass-amherst', 'Amherst, MA', 9500, 'USA'),
    ('University of Delaware', 'delaware', 'Newark, DE', 9500, 'USA'),
    ('Syracuse University', 'syracuse', 'Syracuse, NY', 10000, 'USA'),
    ('University of Oregon', 'oregon', 'Eugene, OR', 9500, 'USA'),
    ('University of Tennessee', 'tennessee', 'Knoxville, TN', 9000, 'USA'),
    ('Auburn University', 'auburn', 'Auburn, AL', 9000, 'USA'),
    ('University of Alabama', 'alabama', 'Tuscaloosa, AL', 9000, 'USA'),
    ('University of South Carolina', 'south-carolina', 'Columbia, SC', 9000, 'USA'),
    ('University of Oklahoma', 'oklahoma', 'Norman, OK', 9000, 'USA'),
    ('Florida State University', 'fsu', 'Tallahassee, FL', 9000, 'USA'),
    ('Iowa State University', 'iowa-state', 'Ames, IA', 9000, 'USA'),
    ('University of Kansas', 'kansas', 'Lawrence, KS', 9000, 'USA'),
    ('University of Nebraska-Lincoln', 'nebraska', 'Lincoln, NE', 9000, 'USA'),
    ('University of Missouri', 'mizzou', 'Columbia, MO', 9000, 'USA'),
    ('University of Kentucky', 'kentucky', 'Lexington, KY', 9000, 'USA'),
    ('Louisiana State University', 'lsu', 'Baton Rouge, LA', 9000, 'USA'),
    ('University of Arkansas', 'arkansas', 'Fayetteville, AR', 8500, 'USA'),
    ('University of Utah', 'utah', 'Salt Lake City, UT', 9000, 'USA'),
    ('University of New Mexico', 'new-mexico', 'Albuquerque, NM', 8500, 'USA'),
    ('University of Mississippi', 'ole-miss', 'Oxford, MS', 8500, 'USA'),
    ('West Virginia University', 'wvu', 'Morgantown, WV', 8500, 'USA'),
    ('Kansas State University', 'kansas-state', 'Manhattan, KS', 8500, 'USA'),
    ('University of Rhode Island', 'uri', 'Kingston, RI', 9000, 'USA'),
    ('University of Vermont', 'uvm', 'Burlington, VT', 9000, 'USA'),
    ('University of New Hampshire', 'unh', 'Durham, NH', 9000, 'USA'),
    ('University of Maine', 'maine', 'Orono, ME', 8500, 'USA'),
    ('University of Hawaii at Manoa', 'hawaii-manoa', 'Honolulu, HI', 9500, 'USA'),
    ('University of Alaska Fairbanks', 'alaska', 'Fairbanks, AK', 8500, 'USA'),
    ('University of Wyoming', 'wyoming', 'Laramie, WY', 8500, 'USA'),
    ('University of Montana', 'montana', 'Missoula, MT', 8500, 'USA'),
    ('University of Idaho', 'idaho', 'Moscow, ID', 8500, 'USA'),
    ('University of Nevada, Reno', 'nevada-reno', 'Reno, NV', 8500, 'USA'),
    ('University of South Dakota', 'south-dakota', 'Vermillion, SD', 8000, 'USA'),
    ('University of North Dakota', 'north-dakota', 'Grand Forks, ND', 8000, 'USA'),
    ('South Dakota State University', 'sdsu', 'Brookings, SD', 8000, 'USA'),
    ('North Dakota State University', 'ndsu', 'Fargo, ND', 8000, 'USA'),
    ('Montana State University', 'montana-state', 'Bozeman, MT', 8500, 'USA'),
    ('Idaho State University', 'idaho-state', 'Pocatello, ID', 8000, 'USA'),
    
    -- Canadian Universities
    ('University of Toronto', 'utoronto', 'Toronto, ON, Canada', 14000, 'Canada'),
    ('McGill University', 'mcgill', 'Montreal, QC, Canada', 14000, 'Canada'),
    ('University of British Columbia', 'ubc', 'Vancouver, BC, Canada', 13000, 'Canada'),
    ('McMaster University', 'mcmaster', 'Hamilton, ON, Canada', 12000, 'Canada'),
    ('University of Alberta', 'ualberta', 'Edmonton, AB, Canada', 12000, 'Canada'),
    ('University of Montreal', 'umontreal', 'Montreal, QC, Canada', 12000, 'Canada'),
    ('University of Waterloo', 'waterloo', 'Waterloo, ON, Canada', 12000, 'Canada'),
    ('Western University', 'western', 'London, ON, Canada', 11000, 'Canada'),
    ('Queen''s University', 'queens', 'Kingston, ON, Canada', 11000, 'Canada'),
    ('University of Calgary', 'ucalgary', 'Calgary, AB, Canada', 11000, 'Canada'),
    ('Dalhousie University', 'dalhousie', 'Halifax, NS, Canada', 10000, 'Canada'),
    ('University of Ottawa', 'uottawa', 'Ottawa, ON, Canada', 10000, 'Canada'),
    ('Simon Fraser University', 'sfu', 'Burnaby, BC, Canada', 10000, 'Canada'),
    ('University of Victoria', 'uvic', 'Victoria, BC, Canada', 10000, 'Canada'),
    ('Laval University', 'laval', 'Quebec City, QC, Canada', 10000, 'Canada'),
    ('York University', 'yorku', 'Toronto, ON, Canada', 9500, 'Canada'),
    ('University of Saskatchewan', 'usask', 'Saskatoon, SK, Canada', 9500, 'Canada'),
    ('University of Manitoba', 'umanitoba', 'Winnipeg, MB, Canada', 9500, 'Canada'),
    ('Carleton University', 'carleton', 'Ottawa, ON, Canada', 9500, 'Canada'),
    ('University of Guelph', 'guelph', 'Guelph, ON, Canada', 9500, 'Canada')
  ) AS t(name, slug, location, price, country)
)
INSERT INTO cms_products (
  name, slug, description, category_type, country, price, 
  status, category_id, stock_status, stock_quantity, 
  features, seo_description
)
SELECT 
  name || ' Diploma' as name,
  slug as slug,
  'Official academic diploma from ' || name || ' located in ' || location || '. Features holographic security, embossed seals, and official verification.' as description,
  'diploma' as category_type,
  country,
  price as price,
  'active' as status,
  (SELECT id FROM category) as category_id,
  'in_stock' as stock_status,
  50 as stock_quantity,
  jsonb_build_array(
    'Embossed university seal',
    'Holographic security features',
    'Official signatures',
    'Watermarked paper',
    'Raised ink printing',
    'UV security elements',
    'Official transcript available',
    'Verification code included'
  ) as features,
  'Get your official diploma from ' || name || ' with authentic security features and verification.' as seo_description
FROM all_diplomas
WHERE NOT EXISTS (
  SELECT 1 FROM cms_products 
  WHERE cms_products.slug = all_diplomas.slug
);